# Generated by Django 4.1.5 on 2023-02-07 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('PLAY', 'PLAY'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('address', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=10)),
                ('nationality', models.CharField(choices=[('Indian', 'Indian'), ('Other', 'Other')], max_length=150)),
                ('city', models.CharField(choices=[('Purnea', 'Purnea'), ('Pune', 'Pune')], max_length=150)),
                ('state', models.CharField(choices=[('Bihar', 'Bihar'), ('Punjab', 'Punjab')], max_length=150)),
                ('pin_code', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('dob', models.DateField()),
                ('className', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_management.classes')),
            ],
        ),
    ]
