# Generated by Django 4.1.5 on 2023-02-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_alter_student_address_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(max_length=150),
        ),
    ]
