# Generated by Django 4.1.5 on 2023-02-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0006_alter_student_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rf_code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
