# Generated by Django 4.1.5 on 2023-02-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0008_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
